### ISSUE TITLE
$ja no longer renders in units describe in configuration

### ISSUE THREAD

**Issue by benjamind** [synthetos/g2#122]
It appears that $ja is being internally scaled down to 0.0 - 1.0 range, so you enter $ja=200000 in configuration and you will get $ja=0.2 back out. This is fine, but the documentation needs updating.

**Comment by aldenhart** [comment]
Yes. Our documentation is lagging behind. $ja is now "junction aggression" not "junction acceleration". We have changed the cornering algorithm to be entirely based on the actual jerk in the cornering move, not an approximation based on centripetal acceleration. $ja is not a unitless value that is nominally 0.75 - 1.00 for most machines. Set to lower for slower cornering, faster to more aggressive (jerky) cornering. Values typically range from 0.25 to 2.00
