### ISSUE TITLE
Due + Gshield settings not being saved

### ISSUE THREAD

**Issue by antbarney** [synthetos/g2#128]
Here is the build info:
[fb]  firmware build             87.01
[fv]  firmware version            0.98
[cv]  configuration version       7.00
[hp]  hardware platform           3.00

After making changes to motor mapping and settings, if the Due is reset or rebooted all the settings are returning to default.

**Comment by antbarney** [comment]
Found this is currently posted as known closing this.

**Comment by chilipeppr** [comment]
Just use the cog wheel icon in the SPJS widget in Chilipeppr to auto re-send your settings every time you connect to the Due. That's how I do it. -John
