### ISSUE TITLE
Support for Radds 1.5 board

### ISSUE THREAD

**Issue by grbd** [synthetos/g2#141]
Hi,

I've recently added support for the radds board to my own fork
http://ooznest.co.uk/RADDS-3D-Printer-Controller-Board
https://github.com/grbd/GBD.OxBot.FirmwareG2
This is what I'm using at the moment with a ooznest Ox CNC

I wasn't sure if to do a pull request because of some of the other changes I've made
This is an overview of the changes I've made to this point

1. I've updated the solution / project file to the latest Atmel Studio 7.0
2. New build definition of "radds15" added to the Makefile
3. New build configuration of "radds15" added to the Project File
4. Build configurtion set to use radds15 as the platform
5. pin out file TinyG2\platform\atmel_sam\board\due\radds15-pinout.h created
6. small change to the TinyG2/stepper.cpp file to allow inverting the stepper enable pins

The way I've done the inverting of the stepper enable pins might not be the best way to do it
but I wasn't sure if there was a better way already inbuilt
(if it were me I'd probably setup the pin defintions differently as a class)

The last commit I made in the fork is just to change the cpu type from AT91SAM3X8C to AT91SAM3X8E
for the arduino due (but it will depend on which device your debugging on, and this setting doesn't
seem to be build configuration specific), also some settings for the segger I'm using

**Comment by aldenhart** [comment]
Thanks for the update. If you want to add this configuration to the project please do so. The edge-100 branch contains the latest project structure. Read the Developers pages for how to include a new target and its configuration. Thanks for the support.
