### ISSUE TITLE
JSON for LEDs

### ISSUE THREAD

**Issue by brookdrumm** [synthetos/g2#152]
We would like to be able to independently address the 3 RGBW LEDs on the new Printrboard G2 via JSON from our Printrhub.
(Made some headway today - Aug. 30, 2016)

**Comment by giseburt** [comment]
I have the temporary version of this implemented in 100.08:

`{_leds:0}` sets them to off (black)
`{_leds:1}` sets them to on (white)
`{_leds:2}` sets them to red
`{_leds:3}` sets them to green
`{_leds:4}` sets them to blue
`{_leds:5}` sets them to orange
`{_leds:6}` sets them to yellow
