### ISSUE TITLE
Link to Due Pinout no longer works, instead you are just sent to the G2 wiki homepage.

### ISSUE THREAD

**Issue by rewsiffer** [synthetos/g2#158]
Title says it all.

**Comment by aldenhart** [comment]
Can you please post the link that fails?

**Comment by rewsiffer** [comment]
Sorry, should have done that in the beginning.

Link: [https://github.com/synthetos/g2/wiki/Arduino-DUE-Pinout-for-tinyG2](url)

It's the "Arduino Due Pinout" link under "Reference" on the main right panel in the wiki.

However, the above link does work so thanks!

**Comment by rewsiffer** [comment]
Also, I just checked and it looks like someone is already modifying it so thanks!
