### ISSUE TITLE
Motor timeouts not working properly

### ISSUE THREAD

**Issue by giseburt** [synthetos/g2#166]
The timeouts for motor disable are not functioning correctly. The `MOTOR_POWER_TIMEOUT` setting appears to be ignored.

What you should see, and it is not:
1) Home X, Y, Z
2) Move Z up some
3) Leave it (supposedly waiting for temperature or whatever), and the Z motor (at least) should not disable.
I have it set to 30 seconds in their config, but when I looked it was using the 0.25 second setting from somewhere else.

**Comment by aldenhart** [comment]
This should now be corrected in edge-100 build 100.11.
