### ISSUE TITLE
LICENSE file at the top level

### ISSUE THREAD

**Issue by giseburt** [synthetos/g2#176]
Should contain the full GPL text.

**Comment by justinclift** [comment]
I can get this done pretty easily.  Which GPL license though, so I know which text to grab? :smile:

**Comment by justinclift** [comment]
Ahhh, looking at a [source](https://github.com/synthetos/g2/blob/edge/g2core/gcode_parser.cpp#L750-L751) file now shows a GPL v2 (only) header.  Kind of obvious in hind sight. :wink:

**Comment by aldenhart** [comment]
I ported this page over from the TinyG repo and modified it for g2core. 
https://github.com/synthetos/g2/wiki/G2core-License

It explains the intent of the licensing and the BeRTOS exception. 

I'll leave this issue open in case you think there's further action required.

**Comment by justinclift** [comment]
Just created a PR adding it to the repo as a file, which I *think* will complete things for this issue. :smile:

**Comment by justinclift** [comment]
License text has been merged into the top level of edge.

Is being merged into edge considered good enough for this issue to be closed, or should we generally wait until code has made its way into master (more stable)?

**Comment by justinclift** [comment]
After thinking about this a bit more... went and looked at the other recently closed PRs'.  Looks like being merged into edge is when things are considered done (generally speaking).

So, closing this now. :smile:

**Comment by giseburt** [comment]
Oh, good point. We somehow need to indicate that all development is done against edge, and all PRs then need to be against edge.

**Comment by justinclift** [comment]
Well, the "do PR's and dev on edge" (paraphrasing) is mentioned a fair amount on the [Development process](https://github.com/synthetos/g2/wiki/Development-Process) page.

The bit I was unsure of was whether getting merged into edge is considered "done" enough for closing an issue, or whether the norm here is to wait for things to potentially stabilise.  eg wait for the new PR'd code to get into master before closing the issue

Seems to be "close the issue when the fix/change/PR is merged into edge".  That's completely fine.  Faster turn around for PR's, and things could always be re-opened / new PR's created to follow up with anyway if needed.

Nothing to worry about. :smile:

**Comment by giseburt** [comment]
No, that's a valid point. If we were using milestones, then I'd say *those* don't close until the PRs involved are merged to master. But we aren't quite there yet…

-Rob
