### ISSUE TITLE
Reporting positions slower if more axes move

### ISSUE THREAD

**Issue by siamect** [synthetos/g2#203]
Thanks for a great project.
But now I have a problem that reporting of positions are slower if i move many axes at the same time. I run version 295d7ba36 and I have enabled 6 axes and that worked fine in 1bc31a6bfd   
If I run one axis there is no problem, two axes are a little slower, three axes are a few seconds and 4 axes the reporting not is not happening unless you run really long distances, 10ths of seconds.  
Thanks again  
Martin

My settings:  
```
#ifndef STATUS_REPORT_MIN_MS
#define STATUS_REPORT_MIN_MS        200                     // (no JSON) milliseconds - enforces a viable minimum
#endif

#ifndef STATUS_REPORT_INTERVAL_MS
#define STATUS_REPORT_INTERVAL_MS   250                     // {si: milliseconds - set $SV=0 to disable
#endif

#ifndef STATUS_REPORT_DEFAULTS                              // {sr: See Status Reports wiki page
#define STATUS_REPORT_DEFAULTS "line","posx","posy","posz","posa","posb","posc","feed","vel","unit","coor","dist","admo","frmo","momo","stat","homz","homy","homx","homa","homb","homc"


```

**Comment by aldenhart** [comment]
The status reports are throttled back to preserve MCU cycles when the load is heavy. What you are seeing is normal operation. Step generation and planning has higher priority than status reporting.
