### ISSUE TITLE
Line number bug in text mode

### ISSUE THREAD

**Issue by alessandrolecce** [synthetos/g2#208]
In Text mode ( I don't know in JSON) gcode with N code  (line numeber) are non report.... just line 0 or -0 or -2
report on serial is:
Line Number: 0
if there is N code in gcode, or nothing if there is not N code in gcode.

I think the problem is in 
gcode_parser.cpp line 623

but I just report to explorer what's happen...I'm not a good C++ programmer :(

**Comment by alessandrolecce** [comment]
in Json mode report line is ok!

**Comment by alessandrolecce** [comment]
ok...the problem is in text_parser.h line: 58 
There is a bug on new implementation.

**Comment by aldenhart** [comment]
Thanks for the heads up. It looks like the printf() format for line numbers in incorrect. We'll fix this in a future update.

**Comment by aldenhart** [comment]
Fixed in PR #211 - build 100.17
