### ISSUE TITLE
Dual Endpoint USB

### ISSUE THREAD

**Issue by aldenhart** [synthetos/g2#22]
This issue is for discussion of the dual endpoint USB function that is documented here:
https://github.com/synthetos/g2/wiki/Dual-Endpoint-USB-Operation

**Comment by cmcgrath5035** [comment]
FYI, when running TinyG2 on Linux, the two ports appear as /dev/ttyADM0 and /dev/ttyADM1. I have not attempted to do anything on the /dev/ttyADM1 port as of yet.
