### ISSUE TITLE
G2CORE_FIRMWARE_BUILD 

### ISSUE THREAD

**Issue by alessandrolecce** [synthetos/g2#239]
in 100.19 was not update

**Comment by aldenhart** [comment]
Point noted. We will try to be more careful with tagging builds in the future.

**Comment by alessandrolecce** [comment]
I Write just for repository correction I'm not finicky. :)

**Comment by aldenhart** [comment]
I appreciate you looking out for this. It's difficult to change at this point, so we'll be more careful in the future. Thanks for your support.
