### ISSUE TITLE
DDA, DWELL, SGI 

### ISSUE THREAD

**Issue by alessandrolecce** [synthetos/g2#241]
Can anyone explain exactly how DDA, DWELL and SGI frequency change step pulse?
What are the relations?

**Comment by alessandrolecce** [comment]
If I'm asking something too long to explain, Can anyone give me a references to understand? Or there is just a reverse code understanding?

**Comment by aldenhart** [comment]
I think the best place is to read the code in the Stepper.cpp file. It's well commented.
