### ISSUE TITLE
Introduce the project in the README

### ISSUE THREAD

**Issue by kasbah** [synthetos/g2#250]
Hey, I was curious about this project but the first few things that you read when you stumble across it are not really very helpful unfortunately. Take a newcomers perspective that has no idea what this project is about. 

> TinyG2 - The Next Generation 

Ok...

> G2 Edge is the branch for beta testing new features under development. New features are developed in feature branches and merged into the edge branch. Periodically edge is promoted to master.

right

>The fb:100 release is a major change from the fb:089 and earlier branches. It represents about a year of development and has many major feature enhancements summarized below. These are described in more detail in the rest of this readme and the linked wiki pages.

hmm

>   New Gcode and CNC features
    3d printing support
    GPIO system enhancements
    Planner enhancements and other operating improvements for high-speed operation

aha! I guess it's about CNC and motor control. No links to further info though

>The project is now called g2core (even if the repo remains g2). As of this release the g2core code base is split from the TinyG code base. TinyG will continue to be supported for the Xmega 8-bit platform, and new features will be added, specifically as related to continued support for CNC milling applications. The g2core project will focus on various ARM platforms, as it currently does, and add functions that are not possible in the 8-bit platform.

AHHRRRG :scream:  :laughing:

**Comment by aldenhart** [comment]
Thanks for the heads up. We'll have to make that more clear.
