### ISSUE TITLE
Windows10 / Atmel Studio 7 compilation

### ISSUE THREAD

**Issue by shczm** [synthetos/g2#252]
Hi,

Followed the instructions carefully, however, tried many times did not succeed. 

1. recipe for target '../Motate/MotateProject/motate/../../Tools/win32/gcc-arm-none-eabi/bin' failed	g2core	C:\github\g2\Motate\MotateProject\motate\Motate.mk	404

2. recipe for target 'win32/gcc-arm-none-eabi-5_4-2016q2-20160622-win32.zip' failed	g2core	C:\github\g2\g2core\Makefile	143

If  ATMEL ICE needed when compiling?

Thanks

**Comment by Dan211** [comment]
This looks like youre missing Motate, did you clone the repository using the --recusive flag?

**Comment by geosmall** [comment]
I'm having the same issue on Win 10 with Atmel Studio 7.

Motate present, --recursive was used.  Builds fine for me on my Linux machine.

![2017-04-01](https://cloud.githubusercontent.com/assets/14177370/24577162/beafd486-1696-11e7-8998-5506fe3d876f.png)

**Comment by geosmall** [comment]
Ok it was my fault for not having git-scm installed (per instructions).  A manual install into Tools/win32/ of gcc-arm-none-eabi compiles correctly.

**Comment by geosmall** [comment]
Looking further this is an issue within Motate repo as Motate.mk is root cause.
