### ISSUE TITLE
Support Printrbot Simple Heated Bed

### ISSUE THREAD

**Issue by giseburt** [synthetos/g2#261]
Some adjustments are necessary to support a heated bed on the Printrbot Simple 1608 (recently rebranded as the "Simple Pro").

This issue will track those changes.

**Comment by pr3sidentspence** [comment]
I've got a Simple Pro I just put the heated bed upgrade on, and it's acknowledging, but ignoring bed temperature commands. Could it be that my firmware isn't recent enough? How could I tell?

EDIT: I have sent the enable heated bed command.

**Comment by justinclift** [comment]
@pr3sidentspence What software are you using to connect to the Simple Pro?

If it's something that can display a list of the commands sent and the responses received, then the version info should be in the first (roughly) response line.  It'll look something like:

```
{"r":{"sys":{"fb":100.26,"fbs":"100.26-10-g1ff7","fbc":"settings_default.h","fv":0.99, ...
```

That example line indicates firmware build 100.26.

Does that help? :smile:

**Comment by giseburt** [comment]
Some firmwares have the heat bed disabled by default. Add this line to the
first few lines of the start.gcode to enable it:

M100.1 ({he3e:t}) ; enable heater 3 - the heat bed

From then the normal Marlin heater commands for the heat bed should start
working.

-Rob

**Comment by pr3sidentspence** [comment]
@giseburt Yes, I've done that. It returns: Recv: `{"r":{"he3e":true},"f":[1,0,18]}`. I'm not sure what the `"f":[1,0,18]` indicates. EDIT: Sorry, that sounded snarky, I didnt mean it that way.

@justinclift I've seen it return `g2core-100.21-81-gd770`, but I have no idea how that compares to Printrbot's final release binary: `G2core170411.bin`. And I'm not sure I am running that one, I have a sneaky feeling that I'm running a post-enabling-gcode but pre-heated-bed announcement firmware.

**Comment by giseburt** [comment]
The latest release is 101.03, found here:
https://github.com/synthetos/g2/releases/tag/101.03

There was a bug where heater 3 (the heat bed) wasn’t getting the Marlin
commands properly. I’m not sure what version it was fixed in, but it is
certainly fixed in the latest version.

-Rob

**Comment by pr3sidentspence** [comment]
Flashed it to Printrbot's last firmware and it's good now.

EDIT: THANKS!

**Comment by justinclift** [comment]
Awesome. :smile:
