### ISSUE TITLE
gQuadratic and gQuintic boards

### ISSUE THREAD

**Issue by shczm** [synthetos/g2#271]
Hi ,

I would like to know more about the gQuadratic and gQuintic boards.
I searched on the internet ,but found nothing.
Can anyone help me?

Thanks

**Comment by aldenhart** [comment]
We are in prototype on both these boards and have not made details available yet. Please keep a watch out for more information, which should be coming shortly. Thanks for your patience.

**Comment by dZlj95** [comment]
Hi,everyone! I am very interested in Atmel SAMS70N19A ARM Cortex M7 processor, Can anyone help me to know how to port the code to this MCU? I had compiled the g2core project,but report some error.
