### ISSUE TITLE
100.26 gShield-pinout.h file missing

### ISSUE THREAD

**Issue by hublerdesignworks** [synthetos/g2#272]
![atmel studio 7 - compile errors](https://cloud.githubusercontent.com/assets/26697527/25487660/1d7c0e5e-2b22-11e7-8791-29a6a55747c9.JPG)

Help...

**Comment by r89m** [comment]
Just had the same issue. Seems it was removed (not sure if intentionally) in c7c8728327ddff132712849f29cfef6784adfe0d 

Running `git revert c7c8728327ddff132712849f29cfef6784adfe0d`, cleaning and rebuilding the solution appeared to work

**Comment by hublerdesignworks** [comment]
That did the job. Thanks!

**Comment by giseburt** [comment]
That's my fault. It came in a pull request and I missed that that file got
deleted. I'll fix that in the next release.

Thank you both for finding this and figuring it out!

**Comment by cmcgrath5035** [comment]
It appears that Riley fixed this issue in  Repository on 9/16/2017. I'll leave this open for Rob or Riley to verify

**Comment by justinclift** [comment]
Closing this, as it was added back in a while ago by @ril3y with e9aba647b9ae0a59b048c14bb0d0fbe423137e44, as mentioned by @cmcgrath5035. :smile:
