### ISSUE TITLE
Homing backs off longer than expected?

### ISSUE THREAD

**Issue by ryansturmer** [synthetos/g2#28]
System appears to back off for a really long time when running the homing cycle:

xlb = 5
xzb = 1
xsv = 60
xlv = 100

https://www.youtube.com/watch?v=AFiD36STgvA

**Comment by Mgilbride** [comment]
Not sure what hardware you are running. But your limit switches must be on separate inputs. You can wire two switches per axis for max min limits of just that axis and tie them to a single axis. But not needed on this hardware unless you are trying to cram some unusual amount of switches on something. And wiki advises against it.

**Comment by stg** [comment]
I had similar problems a while back with strange behaviour with limit switches for all axes connected to the same input. Did not know this was not allowed. Thanks.

**Comment by ryansturmer** [comment]
Seems like something that should be able to work - we have resorted to homing in the ShopBot language rather than G-Code since we can get the performance we want that way, for now.

**Comment by Mgilbride** [comment]
Yes. Agree. Should work with axes that home sequentially. But is code
explicitly looking for signal on relevant inputs configured in settings? I
have not looked at code and have barely gotten g2 working.  And I still
have odd homing behavior.

Am curious as to why one would want network switches on one input when 6
sets of inputs are exposed in hardware and firmware?

**Comment by aldenhart** [comment]
The homing routine homes in sequence ZXYABC. Z is always first to clear the table. They do expect separate switches, but in the newer releases (edge) they don't need to have separate switches if you set up homing to share switches using the {di... settings.

It's still better to have separate switches as that way the machine can back off the closed limit switch (opposite end from the homing switch).
