### ISSUE TITLE
gShield low current pin

### ISSUE THREAD

**Issue by gochisar** [synthetos/g2#280]
Arduino Due pin 2 (physical pin 144) is low current pin. 
This is a problem. X axis losing steps. Pin and card configuration must be replace. 

I am using external servo driver and logic voltage shifter. pin 2 capacitive voltage filling time is weak. 

or can be internal pull_up resistor activation option may solution.

Whatever, best solution not use pin 2 as active pin.

**Comment by aldenhart** [comment]
Thanks for the heads up.
