### ISSUE TITLE
"Arduino Due" doesn't change to "TinyG V2" after flashing

### ISSUE THREAD

**Issue by pufamuf** [synthetos/g2#281]
Hi everyone, I just flashed my Arduino Due R3 with the "Due+gShield V078.03" bin found [here](http://synthetos.github.io/g2/binaries/TinyG2_Due-edge-078.03-default.bin).

My arduino was on COM10, and thus I did the following stuff in Cmd.exe, and the installation was sucessfull. 

> C:\Users\User\Desktop\arduino-flash-tools-master\arduino\bossac\bin>bossac.exe -
> -port=COM10 -U false -e -w -v -b binfile.bin -R
> Erase flash
> Write 125860 bytes to flash
> [==============================] 100% (492/492 pages)
> Verify 125860 bytes of flash
> [==============================] 100% (492/492 pages)
> Verify successful
> Set boot flash true
> CPU reset.

However, the device manager still says I have an "Arduino Due Programming Port (COM10)" connected.

Any advice?

Thank you

**Comment by pufamuf** [comment]
Okay I have solved the issue now.
Something that the OSX guide mentions which the Windows guide does not, is that you need to disconnect the USB cable and plug it into the other port on Arduino due.

**Comment by irshadmgs011** [comment]
> Okay I have solved the issue now.
> Something that the OSX guide mentions which the Windows guide does not, is that you need to disconnect the USB cable and plug it into the other port on Arduino due.

do you compile g2core firmware???

**Comment by justinclift** [comment]
@irshadmgs011 Out of curiosity, are you trying this too and hitting some kind of problem? :smile:

**Comment by justinclift** [comment]
> I want to make G2 core CNC with Due + gshld, I am using Atom 7 with Windows 7 ...

No worries.  Do you have the Arduino Due and gShield yet? :smile:

Also, what is "Atom 7"?  Doing a search for that online shows many "Atom" things, so I'm not sure exactly which one to look at. :wink:

**Comment by irshadmgs011** [comment]
My illusion was to select the board from the compiler or do it by editing the firmware

**Comment by irshadmgs011** [comment]
It was my fault, I mean, I was compiling it with the Atmel studio on Windows 7,
and my english is so weak🤝😭

**Comment by justinclift** [comment]
No worries.  Both will improve with continued practise. :smile:

**Comment by irshadmgs011** [comment]
Can you give your email id???

**Comment by justinclift** [comment]
Errr, what for? :smile: 

My email address shows on my profile page, if that helps?
