### ISSUE TITLE
fusion 360 post config for g2?

### ISSUE THREAD

**Issue by scotthz** [synthetos/g2#319]
Wondering if anyone has a Fusion 360 post config for g2. It comes with a tinyg post, but it doesn't support some things that may be possible with g2. For example, it doesn't allow helical moves.

I'm no expert with Fusion 360 or CAD/CAM in general, just wondering if anyone else has thought about a postprocessor for g2.

**Comment by giseburt** [comment]
This is what I've been using, and is the default setting for the TinyG post:
(You can ignore everything above "Properties".)
![image](https://user-images.githubusercontent.com/386001/36940307-282c47fa-1f06-11e8-911d-c4ecb2281a04.png)

**Comment by giseburt** [comment]
I also recommend enabling smoothing on any operation that allows it, and set it to what's acceptable for your job. For example:
![image](https://user-images.githubusercontent.com/386001/36940331-a2a7bec4-1f06-11e8-9477-c8824f21e18e.png)

**Comment by scotthz** [comment]
Thanks. Allow Helical Moves isn't enabled by default in the TInyG post in my environment, good to know it should work.
