### ISSUE TITLE
Please create a mailing list / IRC / something-not-social-media for g2core

### ISSUE THREAD

**Issue by justinclift** [synthetos/g2#322]
Hiyas,

It's incredibly difficult for new users and people starting out with g2core to communicate with each other to get going.  The Syntheos TinyG forum doesn't meet that need, nor is GitHub issues suited for this purpose.

Is it feasible to create a mailing list (and maybe an IRC channel) for users to communiate with each other?  That'd significantly help new users.

**Comment by hurr1k4ne** [comment]
https://plus.google.com/communities/103099267575816902412

Have a go Here.

Greetings

**Comment by justinclift** [comment]
Thanks, but that's a G+ / social-media thing.  Not exactly a mailing list, IRC channel, or similar. :smile:

eg For people not into social media (many IT folks, myself included), that's not going to work.  Looking for something a bit more "traditional" I guess. :wink:

**Comment by hurr1k4ne** [comment]
I use the g+ group as a Mailinglist. Because i am Not into social Media.

 i got your Point. But thats working for today. Other Channels need a
decision of the official representatives which need some sort of manpower
to maintain.

**Comment by justinclift** [comment]
No worries. :smile:

**Comment by giseburt** [comment]
Hi guys,

We have been thinking of doing a Synthetos public Slack. Does that sound
like it would work in the capacity you’re thinking?

It would be exciting to be able to talk more one-on-one with those that are
interested in g2core.

-Rob

**Comment by justinclift** [comment]
Well... personally I've avoided Slack because it seems to need people to create a brand new account for every project (eg one for g2core, one for -say - Minio, etc), and the client has a terrible reputation as being a resource hog (eg 1.5GB resident ram usage).

But, if that's the only option then sure I could be convinced.  It's at least real-time (like IRC), so would help newbies get over the initial teething bits. :wink:

**Comment by justinclift** [comment]
Going to close this for now, as it's not something that has a clear answer for implementing for away.

We'll probably revisit this later on anyway, after the Community grows in size again. :smile:
