### ISSUE TITLE
Auto tool change request

### ISSUE THREAD

**Issue by nesquik011** [synthetos/g2#324]
Hi , is there option to use auto tool changor spindle ? And how to connect the axis with arduino is there some text i edit so i can set pins ?

**Comment by justinclift** [comment]
Thinking about this a bit, it would probably depend on the autochanger.  What model is yours, and how is it normally driven?

**Comment by nesquik011** [comment]
Check this , nsk
http://www.artcotools.com/nsk-nakanishi-nr40-5100-atc-spindle-50-000rpm.html

**Comment by justinclift** [comment]
Ok, that's the spindle part of an autochanger.  What autochanger do you use?

As a thought... you seem to be asking lots of questions but aren't very specific on your machine.

To make this simpler, what kind of CNC machine do you have, or are you wanting to build your own? :smile:

**Comment by nesquik011** [comment]
building my own and i didnt get the nsk air system yet , or the spindle but  i will buy it soon

**Comment by justinclift** [comment]
Cool.  With the controller for it, what kind of wiring does it use and what signals does it need to receive?

**Comment by nesquik011** [comment]
i dont know there is no much info about it , you need to contact them in Japan

**Comment by nesquik011** [comment]
so can you help with how to make tinyg work with ATC

**Comment by justinclift** [comment]
Probably not, in this specific instance.  If I had the exact hardware here to work with myself, then I probably could.  Want to buy two ATC's and send one to me? :smile:

**Comment by nesquik011** [comment]
lol i wish , i hardly trying to save money for mine hhhhhhh

**Comment by justinclift** [comment]
No worries.  I'll close this issue for now then, and later on if uou have the hardware working we can re-open this to investigate.  :smile:
