### ISSUE TITLE
 canvas's width  of G2 chart turn to 0px 

### ISSUE THREAD

**Issue by yulongWanghb** [synthetos/g2#327]
when using G2 chart to draw path picture ,it shows normal at the first time ,but when i use jquery function  (hide、show ) ，i  find the canvas width become 0 px ,and the data showed in the picture huddled together，i try to change the width of it and failed ,this happened sometimes

**Comment by yulongWanghb** [comment]
version :2.3.13
platform :windows

**Comment by giseburt** [comment]
I believe you have the wrong project. This is a CNC machine firmware called
g2core.

**Comment by yulongWanghb** [comment]
I think i should describle the  clearly ,i draw a path chart with G2 chart successfully in a div mark of html ,it  workes ,and  i have to hide it  by useing jquery function ($.hide（）)，but when i use ($.show ) to show the div ,the chart doesn't work , when i debug the code in chrome ,i find the width of canvas becomes 0px ,i am confused and don't know how to fix it ,can you help me with my puzzle?

**Comment by giseburt** [comment]
This isn’t a web project. This is not “G2 chart.” I’m sorry, but you have
the wrong project.

**Comment by yulongWanghb** [comment]
ok ,whatever thank you very much

**Comment by yulongWanghb** [comment]
I 'm very sorry for my mistake ,i do have the wrong project . i intended to search a project named antivs/G2

**Comment by justinclift** [comment]
@yulongWanghb You should probably close this issue. :wink:
