### ISSUE TITLE
Printing from cura fails after successful print.

### ISSUE THREAD

**Issue by ril3y** [synthetos/g2#332]
If you print directly from cura and the print finishes successfully cura still seems to think a print is "going" and you cannot print again without clicking "abort print" then pressing print via usb.

Cura Version 3.2.1

**Comment by justinclift** [comment]
Any idea what Cura requires (G/Mode?) as "end of job"?

Kind of sounds like M2/M30 isn't getting sent from it and/or not doing the trick.

Meh, sounds like you're already investigating... :smile:
