### ISSUE TITLE
Releases page is missing .elf/.bin for gShield

### ISSUE THREAD

**Issue by justinclift** [synthetos/g2#340]
This is mostly just a reminder for myself, to add the gShield .elf and .bin to our Releases page.

Mainly because for new users it'll provide them a .bin they can use "as is" without having to go through any of the compiling/development steps.

That's preferable, because this will get beginners to "Motors are moving!" earlier on in the process.  Better for motivation. :smile:

**Comment by giseburt** [comment]
BTW: That would be done by editing the travis file. TravisCI automatically pushes builds to the Releases pages.

https://github.com/synthetos/g2/blob/master/.travis.yml

**Comment by justinclift** [comment]
Thanks @giseburt.  That looks really straightforward. :smile:

**Comment by justinclift** [comment]
I've just manually added the gShield [.bin](https://github.com/synthetos/g2/releases/download/100.26/g2core-gShield-100.26.bin) and [.elf](https://github.com/synthetos/g2/releases/download/100.26/g2core-gShield-100.26.bin) files to the existing 100.26 release in the Releases section.

That should get things closer to optimal for now, before the automatic Travis PR approach is completed. :smile:
