### ISSUE TITLE
Xcode Wiki Instructions out of Date

### ISSUE THREAD

**Issue by BDFife** [synthetos/g2#353]
See PR #350 

Xcode build instructions didn't work for me when I followed the instructions on the wiki. https://github.com/synthetos/g2/wiki/Compiling-g2core-on-OS-X-(with-Xcode)

Per @justinclift, the Xcode project may be set up incorrectly. The way the docs are set up right now a naive user (that's me) might assume that Xcode is the preferred build method for OSX.

The command line build process for OSX works great! Consider deprecating the Xcode instructions and guiding users to the terminal until/unless someone is motivated to get Xcode up to date.

**Comment by justinclift** [comment]
Heh Heh Heh

Already done.  Well, I think it is.  Would you be ok to [look over my changes](https://github.com/synthetos/g2/wiki/Getting-Started-with-g2core-Development#compiling-the-code) and confirm they're good from your point of view? :smile:

**Comment by BDFife** [comment]
Perfect, thank you.
