### ISSUE TITLE
Missing status report on feedhold in bernstein-bears branch

### ISSUE THREAD

**Issue by ryansturmer** [synthetos/g2#37]
In prior builds, a status report was sent when the tool came to a halt after a feedhold is issued.  In the latest bernstein-bears branch (latest) 6cd11f93f279f603f2743a532f1079088a42086f this does not appear to happen.  A state change is reported immediately at the time of the feedhold request, but no following report is issued when the tool actually stops.  This makes it impossible to know when the feedhold has actually been completely executed.  An example output follows:

```
info: Stopping jog. [manual]
debug: stopJog() [g2]
g2: --C-1419728349346----> ! [g2]
g2: <-C--1419728349352---- {"r":{},"f":[1,0,17]} [g2]
g2: <-C--1419728349353---- {"qr":18,"qi":1,"qo":0} [g2]
g2: <-C--1419728349381---- {"qr":19,"qi":0,"qo":1} [g2]
g2: <-C--1419728349391---- {"sr":{"posx":-1.509,"vel":50.57,"stat":6,"hold":3}} [g2]
g2: <-C--1419728349446---- {"qr":20,"qi":0,"qo":1} [g2]
g2: <-C--1419728349553---- {"qr":21,"qi":0,"qo":1} [g2]
g2: <-C--1419728349642---- {"sr":{"posx":-1.628,"vel":16.89}} [g2]
```

The last status report above is the last one actually issued by G2.  No further reports were made, even though the system is clearly moving, and at least should issue a status report containing the position once the tool stops moving, (and ideally also changes the "hold" value, if this value still applies with the reworked feedhold system.)

Note that in the example above, the feedhold appears to execute correctly, and the system is still working at this point, I just find myself missing the status report that gives a full tool update when it reaches its resting state, as it did in prior builds.

**Comment by aldenhart** [comment]
stat: is always reported on last SR at this point
