### ISSUE TITLE
STM32 Question

### ISSUE THREAD

**Issue by mirecta** [synthetos/g2#382]
Hi all 
why this (g2) has not port for STM32 MCU which is cheap and more common as ATMEL SAM 
both are cortex m mcu is there any problem ?

**Comment by justinclift** [comment]
Interesting question.  There seems to be stuff around, as mentioned in #372.

Not sure if the code is online, but @vaughanatworld might be ok with putting it up somewhere if there's interest. :smile:

**Comment by mirecta** [comment]
yes can u do it ?
