### ISSUE TITLE
Help needed with syncing XYZ position over DAC

### ISSUE THREAD

**Issue by akym** [synthetos/g2#388]
**Problem:**
I want to use g2core for motion control of 3 linear stages. A custom sensor will be mounted on the stages which gives a +10V analog output. and will be acquired in a DAQ(Datascan 7320/7021). I want to sync the position of the sensor data with the position of the sensor(also at DAQ). One idea is to use the DAC pins of the DUE to write some discrete voltages and read it with DAQ, the measurement software written for DAQ is programmed to identify the different voltage values and interpret them into positions. Alternatively, I could use free pins of the DUE to write PWM to external DACs which can then be connected to the  DAQ. (There are only ~30/40 positions so the resolution of the DAC would not matter much.)

**Ask**
I am quite new with ARM development and the g2core code is quite complicated, can anyone please help me with the programming, Where I need to inject the code? How do I extract the positions from the memory?  How do I write the extracted positions to DAC or free pins?

**Comment by giseburt** [comment]
Hi akym,

I'm not completely sure what you're aiming to achieve, but I may be able to answer part of the question anyway.

If you wish to "push" a motor position to a PWM output (that may then be filtered in hardware into an analog voltage if you wish) you may reuse or copy the [StepDirHobbyServo](https://github.com/synthetos/g2/blob/edge/g2core/device/step_dir_hobbyservo/step_dir_hobbyservo.h) code, which acts as a stepper motor but then outputs a PWM signal generally conditioned for a cheap hobby servo. When a Step signal comes in, the PWM output is modified accordingly.

You would need to ensure that you have 3 Stepper motors and 3 StepDirHobbyServos, and have them routed to the appropriate outputs.

You'll need to make a [modified/custom board configuration](https://github.com/synthetos/g2/wiki/Adding-and-Revising-Boards#making-a-new-board) (perhaps start with the ArduinoDue/gShield configuration). You can use the (unreleased) gQuadratic code as an example (see [`board_stepper.h`](https://github.com/synthetos/g2/blob/edge/g2core/board/gquadratic/board_stepper.h) and [`board_stepper.cpp`](https://github.com/synthetos/g2/blob/edge/g2core/board/gquadratic/board_stepper.cpp)) - note that that board has only two stepper motor drivers and has one Servo driver. You could make it have 3 stepper motor drivers and 3 servo drivers, and in the configuration have 1 stepper and 1 servo per axis.

One thing to watch for is make sure that `MOTORS` is defined ([here](https://github.com/synthetos/g2/blob/edge/g2core/board/ArduinoDue/hardware.h#L47)) to the correct total number of motors (6 as I described above). Unfortunately, there are a few places nt he system that we have hardcoded support for 6 max total motors, so watch out for that. It's relatively easy to fix (they're all instances of copy/paste boilerplate), but it's important to know about. ([Example](https://github.com/synthetos/g2/blob/edge/g2core/config_app.cpp#L214-L216))

-Rob
