### ISSUE TITLE
Ask about stepper.cpp

### ISSUE THREAD

**Issue by hobit26** [synthetos/g2#40]
Why use double check at 364 line:
	if (st_cfg.mot[motor].power_mode == MOTOR_DISABLED) {
		_deenergize_motor(motor);
		return;
	}
and 117 line:
		if (st_cfg.mot[motor].power_mode != MOTOR_DISABLED) {

And why double change power_state at 119 line:
	st_run.mot[motor].power_state = MOTOR_POWER_TIMEOUT_START;
and 388 line:
	st_run.mot[motor].power_state = MOTOR_POWER_TIMEOUT_COUNTDOWN;

**Comment by aldenhart** [comment]
Much of this has changed in the current edge. There may be other changes as well.
