### ISSUE TITLE
bCNC - autolevel

### ISSUE THREAD

**Issue by ziopippona51** [synthetos/g2#471]
Menu autolevel non è più visibile.Ho reinstallato python 2.7.14 + pyserial 3.4 + bCNC, ma il menù autolevel non c'è.
Perché?
#471

**Comment by justinclift** [comment]
Ciao,

Penso che tu abbia creato questo problema per errore nel progetto sbagliato? Invece, intendevi farlo qui? :wink:

&nbsp; &nbsp; https://github.com/vlachoudis/bCNC
