### ISSUE TITLE
Edge chokes on dwell (G4)

### ISSUE THREAD

**Issue by ryansturmer** [synthetos/g2#48]
In the same way described in #44, the G4 command appears to cause G2 to crash irrevocably.  A simple file such as what follows is all it takes:

```
G1X1F120.0
G4P3.0
G1X0F120.0
```

Sending this down all in one packet (on the data channel) actually causes the program to hang before the tool is even set in motion.  On an older build g2@3b00ffad  the hang occurs in the trapezoid planner on the check for a non-NULL motion buffer.  On the tip of edge, the program proceeds, but there is no motion, and subsequent commands are replied to with er:9 "File not open"

This feels related to #45

**Comment by ryansturmer** [comment]
The "file not open" thing is a red herring.  This occurs on my build because after it locks up, I attempt to restart my tool, and one of the first things it does is a {gun:0} command, which provokes the persistence function to try to write a persistent setting, which is not taken because persistence isn't implemented.  It's strange that I only get that error after this crash, and not during a "normal" startup, though.

**Comment by giseburt** [comment]
@ryansturmer I believe this is fixed, and has been for a while. Could you confirm?

Thank you!
