### ISSUE TITLE
Spiral roughing hiccup?

### ISSUE THREAD

**Issue by Mgilbride** [synthetos/g2#492]
Not sure this is an issue. 

I have run some motion tests with a new cnc router build running g2 on a DUE. Gcode is from RhinoCam. I am running firmware version 100.26. 

In one of my tests I am using spiral roughing. At the "same spot" on each pass of the spiral the machine seems to jump back a mm or two causing a noticeable jolt in otherwise smooth motion. I do not see any similar behavior when executing this as a parallel roughing operation. I still need to try this as a circular offset rather than spiral. 

I see no indication that this is mechanical. Any thoughts if this could be a g2 vs RhinoCam issue? I am suspecting some small, hard to see issue with arc interpolation. Not sure how to troubleshoot this behavior and could use some suggestions.

**Comment by ril3y** [comment]
Can you attach the gcode?

**Comment by Mgilbride** [comment]
Absolutely. Attached here. 

Many thanks.

[TestGeometry2.txt](https://github.com/synthetos/g2/files/6217493/TestGeometry2.txt)

**Comment by Mgilbride** [comment]
I need to do more testing. I noticed this page of the post processor. It was set to helical interpolation. There's an option for spiral interpolation. 


![Post Processor](https://user-images.githubusercontent.com/741811/112756911-46866f00-8fb5-11eb-871e-2443dbcab231.png)

**Comment by Mgilbride** [comment]
OK. After another couple of hours testing... I updated the helix/spiral arc interpolation settings in the postprocessor. I utilized arc fitting in the machining settings. All pictured in screenshots here. Updated Gcode also attached here. I get less regularity and severity in the pauses / jumps. I caught an example on a short video. They happen the same place on each layer. But they now don't occur every pass. So, I think this is down to arc interpolation. And it could just be that I am not knowledgeable enough about the settings here. And / or there is a limitation in G2 firmware or RhinoCam.

https://user-images.githubusercontent.com/741811/112767131-f2927f00-8fe2-11eb-8606-676ac2718e38.MOV
![Settings1](https://user-images.githubusercontent.com/741811/112767141-00e09b00-8fe3-11eb-8a89-eeb0979e1a9f.png)
![Settings2](https://user-images.githubusercontent.com/741811/112767142-00e09b00-8fe3-11eb-8f45-8f3d6d9f1a19.png)
![Post2](https://user-images.githubusercontent.com/741811/112767143-00e09b00-8fe3-11eb-81cc-0463da03aea9.png)
![Post3](https://user-images.githubusercontent.com/741811/112767144-00e09b00-8fe3-11eb-9ebe-85b2fe4d37f0.png)
[TestGeometry8.txt](https://github.com/synthetos/g2/files/6218012/TestGeometry8.txt)
