### ISSUE TITLE
9 axis external driver board

### ISSUE THREAD

**Issue by qiwalker** [synthetos/g2#499]
hi, 

i want to develop 9 axis controller g2core using external driver 
before continue to design the expansion pcb 
please advice is it possible to use 
due core board for the MCU it SAM3X8E same like arduino due use
and is there any documentation for 9 axis pin mapping in arduino due ?

need all your help

here's the board

![IMG_20210523_151641](https://user-images.githubusercontent.com/45870169/119253123-e76e6080-bbd9-11eb-9c1a-534792224fa1.jpg)

thanks ^^

**Comment by ril3y** [comment]
This is all going to be in the https://github.com/synthetos/Motate repo.  Take a look in there.
