### ISSUE TITLE
Arduino Due with Edge-preview+gShield not working ///'laser_tool' was not declared in this scope///

### ISSUE THREAD

**Issue by martonpetroczki** [synthetos/g2#504]
I tried to upload the new version but it didn't work. I use an arduino due board with my own shield and the old version worked fine.
This error message appears:
![1](https://user-images.githubusercontent.com/62851502/147504357-b99a0f3f-0193-460f-96b9-e2b09b6291fa.jpg)

I don't understand why the laser is mixed in and what is this? "#warning SPINDLE_ENABLE_OUTPUT_NUMBER is defaulted to 4!"

I found this, but gShield doesn't use it.
![2](https://user-images.githubusercontent.com/62851502/147505150-d9dd91fa-726c-425d-ac02-d0b903a6563a.jpg)

(sorry, my English is bad)

**Comment by justinclift** [comment]
> the old version worked fine.

When you say "the old version", are you meaning an older board, or an older file for uploading, or something else? :smile:

My guess is that you've copied one of the existing settings files ([here](https://github.com/synthetos/g2/tree/edge-preview/g2core/settings)) to `cheapo_laser.h`, and the new one isn't working but the old one is?

> sorry, my English is bad

So far, it's easily good enough. :smile:

**Comment by martonpetroczki** [comment]
I didn't say it exactly.  So the old version is the /master/. I completely deleted the old g2 master folder and I downloaded the edge-preview. What am I doing wrong? :(

**Comment by nickbooties** [comment]
Yeah, looks like  https://github.com/synthetos/g2/commit/423c83f233f1ff414521b9f66170e530d95ad14c broke a bunch of stuff for Due/gShield users. I reverted that and it compiled no problems.

**Comment by martonpetroczki** [comment]
Thanks for your help, it solved the problem.
