### ISSUE TITLE
Status report not returning "pos" or "mpo" for A-axis

### ISSUE THREAD

**Issue by FHUGO1** [synthetos/g2#506]
Hi, 

I am setting up a rotary axis but I can't get g2 to return positioning for the A-axis which in turn prevents zeroing.

All jogs come back in similar fashion:

>>> G21G91G1A90F5000
>>> G90 G21
{"r":{},"f":[1,0,17]}
{"r":{},"f":[1,0,8]}
{"sr":{"vel":4089.87,"dist":1}}
{"sr":{"vel":5000}}
{"sr":{"vel":3061.36}}
{"sr":{"vel":0,"stat":3,"dist":0}}

? also doesn't show any "pos" or "mpo" for A axis

**Comment by MitchBradley** [comment]
It is nearly impossible to provide a complete answer to a question with incomplete information. You told us nothing how you built the code. Look at STATUS_REPORT_DEFAULT in your configuration.
