### ISSUE TITLE
Compiling fail on win7x64 Atmel 6.2.1563

### ISSUE THREAD

**Issue by qtfp** [synthetos/g2#77]
When the linux version still couldn't be cpmpiled, I tried win version.
On win7x64 Atmel 6.2.1563, I getr this :
Build started.
Project "TinyG2.cppproj" (default targets):
Target "PreBuildEvent" skipped, due to false condition; ('$(PreBuildEvent)'!='') was evaluated as (''!='').
Target "CoreBuild" in file "D:\Program Files (x86)\Atmel\Atmel Studio 6.2\Vs\Compiler.targets" from project "E:\download_firefox\g2-edge-0412\g2-edge\TinyG2\TinyG2.cppproj" (target "Build" depends on it):
	Task "RunCompilerTask"
		Shell Utils Path D:\Program Files (x86)\Atmel\Atmel Studio 6.2\shellUtils
		D:\Program Files (x86)\Atmel\Atmel Studio 6.2\shellUtils\make.exe -C "E:\download_firefox\g2-edge\g2-edge\TinyG2" -f "Makefile" TinyG2.elf COLOR=0 VERBOSE=1 OPTIMIZATION=s PLATFORM=gShield MKDIR=gmkdir 
		系統找不到指定的路徑。
		make: Entering directory `E:/download_firefox/g2-edge/g2-edge/TinyG2'
		make: `TinyG2.elf' is up to date.
		make: Leaving directory `E:/download_firefox/g2-edge/g2-edge/TinyG2'

.....
......
......
Build succeeded.
========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========
There are some errors and I copy on the above.

Then I couldnt find the device on the Tools 

Is there any wrong step that I take?
Thanks for the effort:)

**Comment by giseburt** [comment]
Hi @qtfp,

That output appears to be correct.

```
Build succeeded.
========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========
```

That indicates that it built correctly.

"Then I couldnt find the device on the Tools" -- Do you mean an Atmel ICE? The Tools will only show connected debuggers (Atmel ICE or the older Atmel JTAG ICE).

If you haven't already, I suggest starting with the [instructions for compiling](https://github.com/synthetos/g2/wiki/Compiling-G2-on-Windows-(Atmel-Studio-6.2))

Then follow to the windows-specific instructions for flashing the firmware [with an Atmel ICE](https://github.com/synthetos/g2/wiki/Flashing-G2-with-Atmel-Studio6-and-Atmel-ICE) or flashing [without a debugger](https://github.com/synthetos/g2/wiki/Flashing-G2-with-Windows).

-Rob
