### ISSUE TITLE
Comunication lost.

### ISSUE THREAD

**Issue by juanblanco** [synthetos/g2#79]
Hi, I am having an odd problem:
when I plug the Due usb wire it opens a serial port (usually ttyACM0) that doesn't work at all. then I unplug and plug again the usb and then I have two serial interfaces (usually ACM1 and ACM2) only one of these works, some times none works and need to unplug the usb and plug again until it works.
then I can communicate to G2, run gcode and everything works ok, If i send a very large serial command or send a lot of gcode instruccitions at once the communication stop working and the Due doesn't respond, then I have to reset the Due and repeat the mentioned steps. I tested it in ubuntu 13.10, 14.04, on windows 7, and on windows 7 of a different computer. I test it with and without the gshield , the problem persist so I think it is not due noise from steppers or spindle.
I'm starting to believe that is some hardware problem of my Due, but I don't understant how a broken board can open a serial interface one time, two another time, and some how with trial and error I always got it  work.
Someone have experimented this problem before?? how many  ports should be open in normal conditions? 
I am reading the g2 code, is there an easy way to change form native usb to another serial for testing purposes?
thank you very much.

**Comment by ryansturmer** [comment]
@juanblanco 

What version of the code are you currently running?

**Comment by juanblanco** [comment]
Hi, I am using edge compiled a couple of weeks ago.

**Comment by ryansturmer** [comment]
Can you query the firmware build (fb) - also, with the due plugged in, in either configuration, copy the output of `lsusb`

**Comment by cmcgrath5035** [comment]
@juanblanco
Head over to https://github.com/synthetos/g2/wiki and search on USB, there are two items that discuss the Dual USB implementation. 
What are you using to send the serial commands and/or Gcode - CoolTerm, Chilipeppr, ?

**Comment by giseburt** [comment]
@juanblanco Is your problem resolved? If not, do you have any updates?

**Comment by lutorm** [comment]
I had a similar problem with a $15 "Chinarduino" from ebay. Whenever first plugged in, it would not respond, unplugging it and plugging it back in would make it start TinyG. My suspicion is that it got stuck in bootloader mode, but I'm not  sure. In any case, that board was quite sketchy, the headers were soldered all crooked and it was clearly not very high quality. I got a "Sainsmart due" for all of $25, and I'm not having that problem any more. This one always boots TinyG right away, I only have to reset it after uploading a new firmware.

**Comment by ril3y** [comment]
@lutorm just to be clear your Due was sketchy not the gshield?  Right?

**Comment by lutorm** [comment]
Correct. I have my own shield.
