### ISSUE TITLE
Probable error in $$ output Edge build 83.07

### ISSUE THREAD

**Issue by cmcgrath5035** [synthetos/g2#83]
The following rows appear twice, just prior to and just after the $p1* parameters
    [chd] c homing direction          0 [0=search-to-negative, 1=search-to-positive]
    [csv] c search velocity         600 deg/min
    [clv] c latch velocity       100.00 deg/min
    [clb] c latch backoff             5.000 deg
    [czb] c zero backoff              2.000 deg

**Comment by aldenhart** [comment]
Fixed. See edge build 089.xx or later
